Message:
  Title: "&b[MobDrop] "
  MobDropItem: "§f%mob% §6dropped §f%item% §6X §b%item_num% §6!"
  Gobal_MobDropItem: "§6Congratulations! §a%player% §6kill§f %mob% §6and dropped §a%item% §6X §b%item_num% §6!"
  Data_Re_read: "Re-read Data..."
  Data_Re_read_Complete: "Read Complete"

SQL:
  Join_db_connect_error: "&cUnable to connect server database, function failed, please contact with op immediately"
  DataBase_URL: "&aDatabase URL : %URL%"
  DataBase_is_connect: "&aDataBase is connected"
  DataBase_Connecting: "&aConnecting to database..."
  DataBase_Close: "&aDisconnect with database"
  DataBase_Creating: "&aCreating database..."
  DataBase_Create_Success: "&aDatabase created successfully"
  DataBase_Reconnecting: "&cReconnecting to database..."
  DataBase_Selecting: "&aSelecting database【 &e%db% &a】..."
  DataBase_Select_Success: "&aDatabase【 &e%db% &a】Selected successfully"
  DataBase_Select_Fail: "&cDataBase【 &e%db% &a】Select Fail"
  Table_Createing: "&aCreate table【 &e%table% &a】in database【&e%db% &a】..."
  Table_Create_Success: "&aTable【 &e%table% &a】has been successfully created in【 &e%db% &a】database"
  Table_Create_Fail: "&cTable【 &e%table% &c】failed to create in【 &e%db% &c】database"
  Run_cmd: "&aSQL Command:"
  Run_cmd_color: "&2"
  Run_cmd_Success: "&aCommand executed successfully"
  Run_cmd_fail: "&aCommand execution failed"
  Connecting_fail: "&cDataBase Connect Fail"
  can_not_use_command: "&cUnable to use command : 【%cmd%】,connection canceled"

Timer:
  TimeStart: "&aPlease enter in %time% seconds!"
  TimeOut: "&c %time% seconds is up"
  TimeLeft:
    - "&c%%10%% seconds left to enter"
    - "&c%%5%% seconds left to enter"
    - "&c%%4%% seconds left to enter"
    - "&c%%3%% seconds left to enter"
    - "&c%%2%% seconds left to enter"
    - "&c%%1%% seconds left to enter"

Inventory:
  Material_not_found: "&cCan't find proper material"
  Button_not_found: "&cCan't find button"
  Button_not_found_lore: "&cCan't find button, please contact with op"
  Title_error: "&cTitle loading error, please contact with op"
  Type_error: "&cType loading error, please contact with op"
  items_table_get_item_info:
    - ""
    - "&aLeft click"
    - "&aTake this Item"
  items_table_get_item_success: "&fGet item ID:&6%id% &f, name:%name%"
  items_table_get_item_bag_full: "&cinventory full, can't get item"
  items_table_add_success: "&aItem add successfully"
  items_table_add_fail: "&cItem add failed"
  mob_remove_msg: "&bDelete mob '&6%mobname%&b'"
  mob_name_noset_error: "&cName cannot be blank"
  mob_name_same_error: "&cMob name cannot be repeated"
  mob_normal_no_select: "&cPlease select mob"
  mob_normal_same_select: "&cMob is already exists in system"
  mob_item_noset_error: "&cPlease select item"
  mob_item_same_error: "&cThis mob has already got this item"
  mob_item_remove_msg: "&bDelete item '&6%itemname%&b'(&7%itemno%&b) from mob '&6%mobname%&b'"
  mob_item_edit_info:
    - ""
    - "&aLeft click"
    - "&aEdit Item"
  mob_info_lore:
    - ""
    - "&7Items: &2%num%"
  dropitem_info_lore:
    - ""
    - "&7Drop chance: &2%Chance%%"
    - "&7Quantity: &2%Quantity%"

Command:
  CmdCanNotUse: "&cYou Can not use this command here"
  PlayerCanNotUse: "&cYou can't use this command"
  NoPermission: "&cYou don't have this permission"
  CanNotFind: "&cUnknown Command"
  HandNoItem: "&cNo item in hand"
  ItemNotFind: "&cUnknown item"