Message:
  Title: "&b[モンスター ドロップ システム] "
  MobDropItem: "§f%mob% §6が§f %item% §b%item_num% §6個ドロップしました!"
  Gobal_MobDropItem: "§6おめでとう§a %player% §6が§f %mob% §6を倒して§a %item% §b%item_num% §6個ドロップしました!"
  Data_Re_read: "データを再読み込み中..."
  Data_Re_read_Complete: "データの読み込みが完了しました"
SQL:
  Join_db_connect_error: "&cサーバーがデータベースに接続できません。この機能は使用できません。管理者に連絡してください"
  DataBase_URL: "&aデータベースのURL: %URL%"
  DataBase_is_connect: "&aデータベースに接続されています"
  DataBase_Connecting: "&aデータベースに接続中..."
  DataBase_Close: "&aデータベース接続を閉じました"
  DataBase_Creating: "&aデータベースを作成中..."
  DataBase_Create_Success: "&aデータベースの作成に成功しました"
  DataBase_Reconnecting: "&cデータベースに再接続中..."
  DataBase_Selecting: "&aデータベース【 &e%db% &a】を選択中..."
  DataBase_Select_Success: "&aデータベース【 &e%db% &a】の選択に成功しました"
  DataBase_Select_Fail: "&cデータベース【 &e%db% &a】の選択に失敗しました"
  Table_Createing: "&aデータベース【 &e%db% &a】でテーブル【 &e%table% &a】を作成中..."
  Table_Create_Success: "&aテーブル【 &e%table% &a】が【 &e%db% &a】データベースに作成されました"
  Table_Create_Fail: "&cテーブル【 &e%table% &c】の【 &e%db% &c】データベースへの作成に失敗しました"
  Run_cmd: "&aコマンドを実行:"
  Run_cmd_color: "&2"
  Run_cmd_Success: "&aコマンドが正常に実行されました"
  Run_cmd_fail: "&aコマンドの実行に失敗しました"
  Connecting_fail: "&cデータベース接続に失敗しました"
  can_not_use_command: "&cコマンド【%cmd%】は使用できません。接続がキャンセルされました"

Timer:
  TimeStart: "&a%time% 秒以内に入力してください!"
  TimeOut: "&c %time% 秒が経過しました"
  TimeLeft:
    - "&c残り %%10%% 秒で入力可能"
    - "&c残り %%5%% 秒で入力可能"
    - "&c残り %%4%% 秒で入力可能"
    - "&c残り %%3%% 秒で入力可能"
    - "&c残り %%2%% 秒で入力可能"
    - "&c残り %%1%% 秒で入力可能"

Inventory:
  Material_not_found: "&c適切な素材が見つかりません"
  Button_not_found: "&cボタンが見つかりません"
  Button_not_found_lore: "&cボタンが見つかりません。管理者に連絡してください"
  Title_error: "&cタイトルの読み込みエラー。管理者に連絡してください"
  Type_error: "&cアイコンの読み込みエラー。管理者に連絡してください"
  items_table_get_item_info:
    - ""
    - "&a左クリック"
    - "&aアイテムを取得"
  items_table_get_item_success: "&fアイテムID:&6%id% &f, 名前:%name% を取得しました"
  items_table_get_item_bag_full: "&cインベントリがいっぱいでアイテムを取得できません"
  items_table_add_success: "&aアイテムの追加に成功しました"
  items_table_add_fail: "&cアイテムの追加に失敗しました"
  mob_remove_msg: "&bモンスター '&6%mobname%&b' を削除しました"
  mob_name_noset_error: "&c名前は空白にできません"
  mob_name_same_error: "&cモンスター名が重複しています"
  mob_normal_no_select: "&cモンスターを選択してください"
  mob_normal_same_select: "&cシステムに同じモンスターが既に存在します"
  mob_item_noset_error: "&cアイテムを選択してください"
  mob_item_same_error: "&cこのモンスターには同じアイテムが既にあります"
  mob_item_remove_msg: "&bモンスター '&6%mobname%&b' のアイテム '&6%itemname%&b'(&7%itemno%&b) を削除しました"
  mob_item_edit_info:
    - ""
    - "&a左クリック"
    - "&aアイテム設定に入る"
  mob_info_lore:
    - ""
    - "&7アイテム数: &2%num%"
  dropitem_info_lore:
    - ""
    - "&7ドロップ確率: &2%Chance%%"
    - "&7数量: &2%Quantity%"

Command:
  CmdCanNotUse: "&cコンソールではこのコマンドは使用できません"
  PlayerCanNotUse: "&cこのコマンドは使用できません"
  NoPermission: "&cこのコマンドを使用する権限がありません"
  CanNotFind: "&cコマンドが見つかりません"
  HandNoItem: "&c手にアイテムがありません"
  ItemNotFind: "&cアイテムが見つかりません"