Message:
  Title: "&b[怪物掉落系統] "
  MobDropItem: "§f%mob% §6掉落了§f %item% §b%item_num% §6個!"
  Gobal_MobDropItem: "§6恭喜§a %player% §6 將§f %mob% §6殺死後掉落§a %item% §b%item_num% §6個!"
  Data_Re_read: "重新讀取資料..."
  Data_Re_read_Complete: "資料讀取完成"
SQL:
  Join_db_connect_error: "&c伺服器連接資料庫失敗，無法使用此功能，請立即連絡管理員"
  DataBase_URL: "&a資料庫的連結網址%URL%"
  DataBase_is_connect: "&a資料庫已連結"
  DataBase_Connecting: "&a連結資料庫..."
  DataBase_Close: "&a資料庫連結關閉"
  DataBase_Creating: "&a創建資料庫..."
  DataBase_Create_Success: "&a資料庫創建成功"
  DataBase_Reconnecting: "&c重新連結資料庫..."
  DataBase_Selecting: "&a選擇資料庫【 &e%db% &a】中..."
  DataBase_Select_Success: "&a成功選擇資料庫【 &e%db% &a】"
  DataBase_Select_Fail: "&c選擇資料庫【 &e%db% &a】失敗"
  Table_Createing: "&a在資料庫【  &e%db% &a】中創建資料表【 &e%table% &a】..."
  Table_Create_Success: "&a資料表【 &e%table% &a】已成功在【 &e%db% &a】資料庫裡創建"
  Table_Create_Fail: "&c資料表【 &e%table% &c】在【 &e%db% &c】資料庫裡創建失敗"
  Run_cmd: "&a執行指令:"
  Run_cmd_color: "&2"
  Run_cmd_Success: "&a指令成功執行"
  Run_cmd_fail: "&a指令執行失敗"
  Connecting_fail: "&c資料庫連結失敗"
  can_not_use_command: "&c無法使用此指令【%cmd%】,連結取消"

Timer:
  TimeStart: "&a請於 %time% 秒內完成輸入!"
  TimeOut: "&c %time% 秒的時間已到"
  TimeLeft:
    - "&c還剩餘 %%10%% 秒能輸入"
    - "&c還剩餘  %%5%% 秒能輸入"
    - "&c還剩餘  %%4%% 秒能輸入"
    - "&c還剩餘  %%3%% 秒能輸入"
    - "&c還剩餘  %%2%% 秒能輸入"
    - "&c還剩餘  %%1%% 秒能輸入"

Inventory:
  Material_not_found: "&c找不到適當的材料"
  Button_not_found: "&c找不到按鍵"
  Button_not_found_lore: "&c找不到按鍵,請聯絡管理員"
  Title_error: "&c標題讀取錯誤,請聯絡管理員"
  Type_error: "&c圖示讀取錯誤,請聯絡管理員"
  items_table_get_item_info:
    - ""
    - "&a點擊左鍵"
    - "&a拿取道具"
  items_table_get_item_success: "&f獲取道具ID:&6%id% &f, 名稱:%name%"
  items_table_get_item_bag_full: "&c背包已滿，無法獲取道具"
  items_table_add_success: "&a物品增加成功"
  items_table_add_fail: "&c物品增加失敗"
  mob_remove_msg: "&b刪除怪物 '&6%mobname%&b'"
  mob_name_noset_error: "&c名稱不能是空白"
  mob_name_same_error: "&c怪物名稱重複"
  mob_normal_no_select: "&c請選擇怪物"
  mob_normal_same_select: "&c系統內已有重複怪物"
  mob_item_noset_error: "&c請選擇物品"
  mob_item_same_error: "&c此怪物已有重複物品"
  mob_item_remove_msg: "&b刪除怪物 '&6%mobname%&b' 的物品 '&6%itemname%&b'(&7%itemno%&b)"
  mob_item_edit_info:
    - ""
    - "&a點擊左鍵"
    - "&a進入設定物品"
  mob_info_lore:
    - ""
    - "&7物品數量: &2%num%"
  dropitem_info_lore:
    - ""
    - "&7掉落機率: &2%Chance%%"
    - "&7數量: &2%Quantity%"

Command:
  CmdCanNotUse: "&c後台無法使用此指令"
  PlayerCanNotUse: "&c無法使用此指令"
  NoPermission: "&c無使用此指令的權限"
  CanNotFind: "&c查無此指令"
  HandNoItem: "&c手上沒有物品"
  ItemNotFind: "&c查無此物品"
  
Mobs:
  #1.13
  BAT: "蝙蝠"
  BLAZE: "烈焰使者"
  CAVE_SPIDER: "洞穴蜘蛛"
  CHICKEN: "雞"
  COD: "鱈魚"
  COW: "牛"
  CREEPER: "苦力怕"
  DOLPHIN: "海豚"
  DONKEY: "驢子"
  DROWNED: "沉屍"
  ELDER_GUARDIAN: "原古深海守衛"
  ENDERMAN: "終界使者"
  ENDERMITE: "終界蟲"
  ENDER_DRAGON: "終界龍"
  EVOKER: "喚魔者"
  GHAST: "幽靈水母"
  GIANT: "巨人"
  GUARDIAN: "深海守衛"
  HORSE: "馬"
  HUSK: "屍殼"
  ILLUSIONER: "喚魔者"
  IRON_GOLEM: "鐵巨人"
  LLAMA: "羊駝"
  MAGMA_CUBE: "烈焰史萊姆"
  MUSHROOM_COW: "蘑菇牛"
  MULE: "騾" 
  OCELOT: "貓"
  PARROT: "鸚鵡"
  PHANTOM: "夜魅"
  PIG: "豬"
  PIG_ZOMBIE: "殭屍豬人"
  POLAR_BEAR: "北極熊"
  PUFFERFISH: "河豚"
  RABBIT: "兔子"
  SALMON: "鮭魚"
  SHEEP: "羊"
  SHULKER: "界伏蚌"
  SILVERFISH: "蠹魚"
  SKELETON: "骷髏"
  SKELETON_HORSE: "骷髏馬"
  SLIME: "史萊姆"
  SNOWMAN: "雪人"
  SPIDER: "蜘蛛"
  SQUID: "魷魚"
  STRAY: "流髑"
  TROPICAL_FISH: "熱帶魚"
  TURTLE: "海龜"
  VEX: "鬼"
  VILLAGER: "村民"
  VILLAGERGOLEM: "鐵人"
  VINDICATOR: "衛道士"
  WITCH: "巫婆"
  WITHER_SKELETON: "凋零骷髏"
  WITHER_SKULL: "凋零怪"
  WOLF: "狼"
  ZOMBIE: "殭屍"
  ZOMBIE_HORSE: "殭屍馬"
  ZOMBIE_PIGMAN: "殭屍豬人"
  ZOMBIE_VILLAGER: "殭屍村民"
  # 1.14
  CAT: "貓"
  FOX: "狐狸"
  PANDA: "熊貓"
  PILLAGER: "掠奪者"
  RAVAGER: "劫毀獸"
  TRADER_LLAMA: "商駝"
  WANDERING_TRADER: "流浪商人"
  # 1.15
  BEE: "蜜蜂"
  # 1.16
  HOGLIN: "豬布獸"
  PIGLIN: "豬布林"
  STRIDER: "熾足獸"
  ZOGLIN: "豬屍獸"
  ZOMBIFIED_PIGLIN: "殭屍化豬布林"
  # 1.16.2
  PIGLIN_BRUTE: "豬布林蠻兵"
  # 1.17
  AXOLOTL: "六角恐龍"
  GLOW_SQUID: "螢光魷魚"
  GOAT: "山羊"